# Generated by Django 4.2.7 on 2023-11-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentname',
        ),
    ]
