# Generated by Django 4.2.7 on 2023-11-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_delete_teacher_remove_student_studentname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
