# Generated by Django 4.2.7 on 2023-11-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_teacher_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teachername',
            new_name='username',
        ),
    ]
