# Generated by Django 4.2.7 on 2023-11-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0007_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
